Reviewer response
rokitalab/clk1-splicing pull request #6
Opened 2024-11-11 21:10 UTC by naqvia

PR responding to [reviewer concerns](https://docs.google.com/document/d/1E19M0Ic77Xs5ef6YmqIU7nq7qlOnuj2MNFCTZaEojYg/edit?pli=1&tab=t.0).

2024-11-14 16:03 UTC, jharenza reviewed
Looks like CLK tpm plot is being saved twice in two different directories. Can you also print out the mean TPMs to a table so we can add these to results?

2024-11-15 20:36 UTC, naqvia commented
I have posted the histogram for CLK1 TPMs and depmap scores for Reviewers #1/#2

2024-11-15 20:55 UTC, naqvia commented
**Note: This will make more sense AFTER you read my reviewer responses!**

2025-01-06 16:44 UTC, jharenza requested changes
requesting some changes to CLK1-splicing_correlations - suggest we just remove script 08 and corresponding plots to keep this PR clean, since they are being worked on it another PR. Also asking for one more column in the table. I cleaned up the other two modules, extraneous scripts/unused scripts.

2025-01-06 16:44 UTC, jharenza commented on analyses/splicing_events_functional_sites/04-plot_splicing_across_functional_sites.R
> +  dplyr::rename(Differential_freq=Frequency,
Can you add here the N in the other direction as well?

2025-01-06 16:44 UTC, jharenza commented on analyses/CLK1-splicing_correlations/08-plot-Ex4PSI-correlations.R
> +suppressPackageStartupMessages({
Since these plots are in #7, should we remove from this PR?

2025-01-10 18:54 UTC, naqvia commented
Please review: 04-plot_splicing_across_functional_sites.R and associated tables

2025-01-10 21:39 UTC, jharenza commented on analyses/CLK1-splicing_correlations/08-plot-Ex4PSI-correlations.R
> +suppressPackageStartupMessages({
i removed these

2025-01-10 21:39 UTC, jharenza approved these changes
👍

2025-01-10 21:55 UTC, merged