CLK1 exon 4 variation
rokitalab/clk1-splicing pull request #7
Opened 2024-11-19 17:07 UTC by naqvia

Compute variation for CLK1 Exon 4 in samples with high CLK1 expression

2024-12-06 19:57 UTC, jharenza commented on analyses/CLK1-splicing_correlations/08-plot-Ex4-PSI-all-tumors.R
> +pedr_rmats <- file.path("~/d3b_coding/neoepitope-identification/data/GSE243682_normal_splice-events-rmats.tsv.gz")
```suggestion
gtex_rmats <- file.path("~/d3b_coding/neoepitope-identification/data/gtex-brain-under40-harmonized-splice-events-rmats.SE.tsv.gz")
pedr_rmats <- file.path("~/d3b_coding/neoepitope-identification/data/GSE243682_normal_splice-events-rmats.tsv.gz")
```

do we need to put a new release together

2024-12-09 14:55 UTC, naqvia commented
To summarize the tpm isoform plot. There are 32 tumors that are > .8239 (highest pediatric percentage -- frontal cortex). 
```
# A tibble: 9 × 2
  plot_group                     n
  <fct>                      <int>
1 Craniopharyngioma              3
2 Ependymoma                    11
3 Choroid plexus tumor           2
4 Mesenchymal tumor              2
5 Low-grade glioma               9
6 Schwannoma                     1
7 Medulloblastoma                1
8 Mixed neuronal-glial tumor     2
9 DIPG or DMG                    1
```

There are 15 HGGs that are greater than the Pons ctrl. 
![image](https://github.com/user-attachments/assets/0124f5f1-87ba-43a3-bd33-ef90d3d72002)

We can argue that these may be unusually elevated with CLK1 Ex 4 transcripts.

2025-01-06 15:48 UTC, jharenza requested changes
Please update the data release folder so that I can rerun this/update the figures.

For the CLK1 exon 4 transcript figures compared to controls, can you update text for consistency:
- change y-axis to "Proportion CLK1 exon 4 inclusion transcript"
- Write out "Cell Type Controls"
- "Evo-Devo"
- "GTEx"
- "Pediatric normals"
- "PBTA" instead of "Tumors" - can you make this the first panel?

2025-01-14 15:10 UTC, jharenza commented on analyses/CLK1-splicing_correlations/11-plot-clk1-ex4-transcripts-by-age-gtex.R
> +
update paths

2025-01-14 15:10 UTC, jharenza commented on analyses/CLK1-splicing_correlations/12-plot-clk1-ex4-transcripts-by-age.R
> +ped_trans_file = "~/d3b_coding/neoepitope-identification/data/GSE243682_normal_rna-isoform-expression-rsem-tpm.rds"
update paths

2025-01-14 15:11 UTC, jharenza commented on analyses/CLK1-splicing_correlations/README.md
> +* `10-plot-clk1-ex4-transcripts-hgg-normals.R` plot CLK1 Ex 4 transcripts proportion in tumors and control samples
add scripts 11-12 here

2025-01-14 15:12 UTC, jharenza commented on analyses/CLK1-splicing_correlations/10-plot-clk1-ex4-transcripts-hgg-normals.R
> +  "Middle Adult")
I can try to update this once all changes are in, it needs a fct_relevel, not a c()

2025-01-14 15:13 UTC, jharenza reviewed
hey @naqvia this seems almost ready - can you delete the plots and rerun the entire module once scripts 11-12 paths are updated - i think there may be some old plots lying around.

2025-02-03 18:59 UTC, naqvia commented
Please review and merge. @jharenza

2025-02-11 16:54 UTC, jharenza commented
>Rscript --vanilla 11-plot-clk1-ex4-transcripts-by-age-gtex.R

Attaching package: ‘dplyr’

The following objects are masked from ‘package:stats’:

    filter, lag

The following objects are masked from ‘package:base’:

    intersect, setdiff, setequal, union

Error in library(coin) : there is no package called ‘coin’
Execution halted

2025-02-11 16:56 UTC, jharenza commented
also 
>Rscript --vanilla 12-plot-clk1-ex4-transcripts-by-age.R 
Rows: 12772 Columns: 6
── Column specification ──────────────────────────────────────────────────────────────────────────────────────────────────
Delimiter: "\t"
chr (6): Kids_First_Participant_ID, Kids_First_Biospecimen_ID, cohort, cance...

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.
Rows: 8489 Columns: 65
── Column specification ──────────────────────────────────────────────────────────────────────────────────────────────────
Delimiter: "\t"
chr (44): Kids_First_Participant_ID, Kids_First_Biospecimen_ID, sample_id, a...
dbl (17): OS_days, EFS_days, age_at_diagnosis_days, age_at_event_days, age_a...
lgl  (4): cell_line_composition, cell_line_passage, gtex_group, gtex_subgroup

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.
Error: object 'expr_tpm_tumor_file' not found
Execution halted

2025-02-11 21:14 UTC, naqvia commented
Fixed the file issue. Coin library needs to be installed, so will make a Docker update that would need to address this

2025-02-12 19:55 UTC, naqvia commented
Please review and merge #24 and then re-run this module.

2025-02-13 20:10 UTC, jharenza approved these changes
all good now

2025-02-14 14:29 UTC, merged